
# This workflow uploads artifacts of Compose via jpackage using Gradle.

name: Upload-Artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  upload-macos:
    # only runs if the PR has been merged
#    if: github.event.pull_request.merged == true
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: '14'
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: JPackage using Gradle
        run: ./gradlew jpackage
      - name: Upload JPackage artifact
        uses: actions/upload-artifact@v2
        with:
          name: an-artifact
          path: build/jpackage/